const constants = {
  OVERLAY_ACTIVE_DURATION: 5000,
  OVERLAY_FADE_DURATION: 250,
  OVERLAY_BUFFER_FADE_OUT_DELAY: 2000,

  BIG_ICON_SCALE: 0.12,
  MEDIUM_ICON_SCALE: 0.08,
  SMALL_ICON_SCALE: 0.06,
};

export default constants;
